from enum import Enum

DEFAULT_LINE_WIDTH = 2.0
DEFAULT_MARKER_SIZE = 6.0
DEFAULT_FONT_SIZE = 12
DEFAULT_TITLE_FONT_SIZE = 14
DEFAULT_LABEL_FONT_SIZE = 12
DEFAULT_TICK_FONT_SIZE = 10
DEFAULT_LEGEND_FONT_SIZE = 10
DEFAULT_LINE_STYLE = "-"
DEFAULT_MARKER = "o"
DEFAULT_GRID = True
DEFAULT_COLOR_SCHEME = "default"
DEFAULT_PLOT_TYPE = "line_2d"
DEFAULT_GRID_MODE = "auto"
DEFAULT_GRID_DENSITY = 1.0
DEFAULT_GRID_LABEL_DENSITY = 1.0

DEFAULT_SCATTER_3D_DEFAULT_COORD_INDEX = 0

DEFAULT_FIGURE_SIZE = (8, 6)
DEFAULT_SUBPLOT_INDEX = 111
DEFAULT_LAYOUT_MARGINS = (0, 0, 0, 0)

DEFAULT_PLOT_BG = "#fafafa"
DEFAULT_PLOT_FG = "#323232"

DEFAULT_GRID_ALPHA = 0.3
DEFAULT_MINOR_GRID_ALPHA = 0.15
DEFAULT_GRID_RELATIVE_DIVISOR = 10.0

DEFAULT_SINGLE_POINT_SIZE = 100
DEFAULT_ZORDER = 5
DEFAULT_SCATTER_3D_ALPHA = 0.7
DEFAULT_CONTOUR_ALPHA = 0.8
DEFAULT_CONTOUR_LINE_WIDTH = 0.5
DEFAULT_CONTOUR_TRIANGULAR_ALPHA = 0.8
DEFAULT_CONTOUR_TRIANGULAR_LINE_WIDTH = 0.3

DEFAULT_COLORMAP_RESOLUTION = 256
DEFAULT_Z_EDGE_EPSILON = 1e-10
DEFAULT_NORMALIZED_EPSILON = 1e-12

DEFAULT_TRIANGULAR_GRID_ALPHA = 0.3
DEFAULT_TRIANGULAR_GRID_LINE_WIDTH = 0.1
DEFAULT_TICK_LINE_WIDTH = 0.8
DEFAULT_TRIANGLE_BORDER_LINE_WIDTH = 1.0

COMPOSITION_TOLERANCE_LOW = 0.99
COMPOSITION_TOLERANCE_HIGH = 1.01

DEFAULT_SINGLE_TICK_LABEL_OFFSET = -0.015
DEFAULT_ELEMENT_LABEL_OFFSET = -0.026
DEFAULT_APEX_LABEL_OFFSET = 0.03
DEFAULT_LABEL_DISTANCE = 0.02

DEFAULT_TICK_HALF_LENGTH_RATIO = 0.5

DEFAULT_TRIANGULAR_COORD_FACTOR = 0.5

DEFAULT_COLORBAR_TICK_COUNT = 9

DEFAULT_CONTOUR_TRIANGULAR_HEIGHT_FACTOR = 0.8660254037844386
DEFAULT_CONTOUR_TRIANGULAR_XLIM = [-0.1, 1.1]
DEFAULT_CONTOUR_TRIANGULAR_YLIM = [-0.15, 1.0]
DEFAULT_CONTOUR_TRIANGULAR_TICK_POSITIONS = [0.2, 0.4, 0.6, 0.8]
DEFAULT_CONTOUR_TRIANGULAR_TICK_LENGTH = 0.02
DEFAULT_CONTOUR_TRIANGULAR_ELEM_LABELS = ["A", "B", "C"]
DEFAULT_CONTOUR_TRIANGULAR_COLORBAR_LABEL = "Z_{ABC}"
DEFAULT_CONTOUR_TRIANGULAR_LEVELS = 20

PLOT_TYPE_LINE_2D = "line_2d"
PLOT_TYPE_SCATTER_2D = "scatter_2d"
PLOT_TYPE_SCATTER_3D = "scatter_3d"
PLOT_TYPE_SURFACE_3D = "surface_3d"

COLOR_ALGORITHM_LINEAR = "linear"
COLOR_ALGORITHM_HARMONIC = "harmonic"
COLOR_ALGORITHM_COLORWHEEL = "colorwheel"

GRID_MODE_ABSOLUTE = "absolute"
GRID_MODE_RELATIVE = "relative"
GRID_MODE_AUTO = "auto"


class ColorAlgorithm(Enum):
    LINEAR = COLOR_ALGORITHM_LINEAR
    HARMONIC = COLOR_ALGORITHM_HARMONIC
    COLORWHEEL = COLOR_ALGORITHM_COLORWHEEL


COLOR_SCHEME_DEFAULT = "default"

THEME_COLORS_DEFAULT = {
    "primary": "#1f77b4",
    "secondary": "#ff7f0e",
}

THEME_PRESETS = ((COLOR_SCHEME_DEFAULT, THEME_COLORS_DEFAULT),)

DEFAULT_ALGORITHM = ColorAlgorithm.LINEAR
DEFAULT_THEME_PRESET = COLOR_SCHEME_DEFAULT

UI_THEME_PRIMARY_DEFAULT = "#C62828"
UI_THEME_SECONDARY_DEFAULT = "#1A1A1A"
