from enum import Enum

DEFAULT_LINE_WIDTH = 2.0
DEFAULT_MARKER_SIZE = 6.0
DEFAULT_FONT_SIZE = 12
DEFAULT_LINE_STYLE = "-"
DEFAULT_MARKER = "o"
DEFAULT_GRID = True
DEFAULT_COLOR_SCHEME = "default"
DEFAULT_PLOT_TYPE = "line_2d"

PLOT_TYPE_LINE_2D = "line_2d"
PLOT_TYPE_SCATTER_2D = "scatter_2d"
PLOT_TYPE_SCATTER_3D = "scatter_3d"
PLOT_TYPE_SURFACE_3D = "surface_3d"

COLOR_ALGORITHM_LINEAR = "linear"
COLOR_ALGORITHM_HARMONIC = "harmonic"
COLOR_ALGORITHM_COLORWHEEL = "colorwheel"


class ColorAlgorithm(Enum):
    LINEAR = COLOR_ALGORITHM_LINEAR
    HARMONIC = COLOR_ALGORITHM_HARMONIC
    COLORWHEEL = COLOR_ALGORITHM_COLORWHEEL


COLOR_SCHEME_DEFAULT = "default"

THEME_COLORS_DEFAULT = {
    "primary": "#1f77b4",
    "secondary": "#ff7f0e",
}

THEME_PRESETS = ((COLOR_SCHEME_DEFAULT, THEME_COLORS_DEFAULT),)

DEFAULT_ALGORITHM = ColorAlgorithm.LINEAR
DEFAULT_THEME_PRESET = COLOR_SCHEME_DEFAULT
