# Miedema Module Info
# This module is also an official example of how to create a module for MoltenMeta.
# For more information, please refer to our official documentation.

[module]
# The package name should be the same as the name of your module's python entry point file (without the .py extension).
package_name = "miedema_module"
entry_class = "MiedemaCalc"
all_methods = [
    "calculateSingle",
    "calculateRange"
]

# The type determines the domain to which the module belongs,
# and the category determines the path within that domain.
type = "simulation"
category = "enthalpy_of_mixing"

# This name is just for displaying. To clarify the package name, see "package_name"
name = "Miedema Module"
version = "1.0.0"
author = "Weichky"
license = "MIT"
description = "Miedema module for calculating enthalpy of mixing"

[data]
# This is the path to the csv file
csv = "miedema_element_properties.csv"
# [WIP]
# If you don't want to save the data to database, you can set this to false
# Then every time you run the module, it will read the data from the csv file
save_to_database = true
table_name = "miedema_element_properties"
columns = [
    "element_id",
    "is_transition_metal",
    "n_ws_13",
    "phi",
    "v_23",
    "mu",
    "r_over_p"
]

[calculateSingle.inputs]
symbol = [
    "elem_A",
    "elem_B",
    "x_A"
]
latex = [
    "elem_A",
    "elem_B",
    "x_A"
]
description = [
    "Element A's id (element number in the periodic table)",
    "Element B's id (element number in the periodic table)",
    "Mole fraction of element A"
]
# You can leave unit empty
# In this case, we don't automatically specify the unit in the software
# You have to specify the unit yourself
unit = [
    "",
    "",
    ""
]

input_method = "composition_tool"

composition_tool.mode = "mole_fraction"
composition_tool.max_components = 2
composition_tool.map = [
    ["elem_A", 0],
    ["elem_B", 2],
    ["x_A", 1]
]

[calculateSingle.outputs]
symbol = [
    "Delta_H_mix"
]
latex = [
    "\\Delta H_{mix}"
]
description = [
    "Enthalpy of mixing"
]
unit = [
    "kJ/mol"
]
can_be_used_as_input = true

# Not nessary to specify, just for human readability.
is_collection = false

[calculateSingle.plot]
plotType = "scatter_2d"
x = "x_A"
xLabel = "x_A"
y = ["Delta_H_mix"]
yLabels = ["\\Delta H_{mix}"]
title = "Enthalpy of Mixing"

[calculateRange.inputs]
symbol = [
    "elem_A",
    "elem_B",
    "x_A_start",
    "x_A_end",
    "n_points"
]
latex = [
    "elem_A",
    "elem_B",
    "x^\\text{start}_A",
    "x^\\text{end}_A",
    "n_\\text{points}"
]
description = [
    "Element A's symbol (e.g. Al, Si)",
    "Element B's symbol (e.g. Al, Si)",
    "Starting mole fraction of element A",
    "Ending mole fraction of element A",
    "Number of points"
]
unit = [
    "",
    "",
    "",
    "",
    ""
]

input_method = "raw"

raw.method_map = [
    ["elem_A", "element_symbol_input"],
    ["elem_B", "element_symbol_input"],
    ["x_A_start", "float_input"],
    ["x_A_end", "float_input"],
    ["n_points", "int_input"]
]

[calculateRange.outputs]
symbol = [
    "Delta_H_mix"
]
latex = [
    "\\Delta H_{mix}"
]
description = [
    "Enthalpy of mixing"
]
unit = [
    "kJ/mol"
]
can_be_used_as_input = true
is_collection = true

[calculateRange.plot]
plotType = "line_2d"
x = "x_A"
xLabel = "x_A"
y = ["Delta_H_mix"]
yLabels = ["\\Delta H_{mix}"]
title = "Enthalpy of Mixing vs Composition"