# Miedema Module Info
# This module is also an official example of how to create a module for MoltenMeta.
# For more information, please refer to our official documentation.

[module]
name = "Miedema Module"
version = "1.0.0"
author = "Weichky"
license = "MIT"
description = "Miedema module for calculating enthalpy of mixing"
category = "enthalpy_of_mixing"

[[inputs]]
symbol = "x_A"
description = "Mole fraction of element A"
# You can leave unit empty
# In this case, we don't automatically specify the unit in the software
# You have to specify the unit yourself
unit = ""
required = true

[[outputs]]
symbol = "\\Delta H_{mix}"
description = "Enthalpy of mixing"
unit = "kJ/mol"
can_be_used_as_input = true

[data]
# This is the path to the csv file
csv = "miedema_element_properties.csv"
# [WIP]
# If you don't want to save the data to database, you can set this to false
# Then every time you run the module, it will read the data from the csv file
save_to_database = true
table_name = "miedema_element_properties"
columns = [
    "element_id",
    "is_transition_metal",
    "n_ws_13",
    "phi",
    "v_23",
    "mu",
    "r_over_p"
]